package com.shc.automation.api.test.framework.entities;

public enum TestStepType {
	STEP, SUBSTEP, INNER_SUBSTEP, VERIFICATION_STEP, DATA_CAPTURE, VERIFICATION_RESULT, VERIFICATION_SUBSTEP, EXCEPTION, ERRORMESSAGE, ERRORMESSAGEDETAILS;
}
